name: Download Playlist and Liked Songs from Youtube
on: 
  schedule:
  - cron: '0 18 * * 1,3,5'
  push:
    branches:
      - master

jobs:
  setup:
    name: Environment Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python Requirements
        run: pip install -r requirements.txt
      - name: Setup ffmpeg
        uses: AnimMouse/setup-ffmpeg@v1
      - name: Setup youtube-dl
        uses: AnimMouse/setup-youtube-dl@v1
      # - name: install youtube-dl dependencies
        # run: |
        #   sudo apt-get update
        #   sudo apt-get install -y youtube-dl ffmpeg
        #   which youtube-dl

  download:
    name: Download Playlist and Liked songs + Store
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Downloading Playlists
        run: |
          cp archive.txt tmp_archive.txt
          echo "Downloading 'ESCAPADE' Playlist"
          make download_songs_from_playlist youtube_playlist=https://music.youtube.com/playlist?list=PLzx7xtGqjNzo5-L7RCEZEP9cOLlYBQrH1
          # echo "Downloading 'Sweet' Playlist"
          # echo "Downloading 'Emo Kid' Playlist"
          # echo "Downloading 'Thuggy' Playlist"
          # echo "Downloading 'Anime' Playlist"
      # - name: Download Liked Songs from user auth
      - name: Move File into Download directory
        run: |
          mkdir downloads
          mv *.mp3 downloads
          ls downloads
      - name: Update archive.txt file
        run: |
          echo "Number of songs downloaded: "
          diff --unchanged-group-format='' archive.txt tmp_archive.txt | wc -l
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add archive.txt
          git commit -m 'updated archive file'
          git push
      # - name: Upload downloaded songs [ TODO ]
